name: Deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Docker_Hub:
    name: Docker Hub
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  QA:
    needs: Docker_Hub
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      github_environment_url: https://qa-metabase.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production:
    needs: [Docker_Hub, QA]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://metabase.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production_Canada:
    needs: [Docker_Hub, QA]
    name: Production (Canada)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Canada)
      github_environment_url: https://metabase.ca.hypothes.is/
      aws_region: ca-central-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
