name: Deploy

on:
  workflow_dispatch:
    inputs: 
      Version:
        description: "The docker image tag to deploy. Defaults to latest"
        required: true
        default: 'latest'
      Environment:
        type: choice
        description: "The environment to deploy. Can be either: 'qa' or 'prod'."
        required: true
        default: 'qa'
        options:
          - qa
          - prod
      Region:
        type: choice
        description: "The AWS region to target. Can be either: 'us-west-1', or 'ca-central-1', or 'all'."
        required: true
        default: 'all'
        options:
          - us-west-1
          - ca-central-1
          - all

permissions:
  id-token: write # required to use AWS OIDC auth

env:
  APP: 'metabase'
  TYPE: 'deploy'
  ENV: ${{ github.event.inputs.Environment }}
  REGION: ${{ github.event.inputs.Region }}
  APP_DOCKER_VERSION: ${{ github.event.inputs.Version }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gha_deploy
        role-duration-seconds: 900
        aws-region: us-west-1
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: hypothesis/dummy-deploy
        ssh-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: install boto3
      run: pip install boto3 pyaml
    - name: Deploy new version
      run: |
        ./bin/init.sh
