name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      staging:
        type: boolean
        description: Redeploy Staging
      production:
        type: boolean
        description: Redeploy Production
      production_canada:
        type: boolean
        description: Redeploy Production (Canada)
jobs:
  staging:
    name: Staging
    if: inputs.staging
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Staging
      github_environment_url: https://metabase.staging.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: staging
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://metabase.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_canada:
    name: Production (Canada)
    if: inputs.production_canada
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Canada)
      github_environment_url: https://metabase.ca.hypothes.is/
      aws_region: ca-central-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: prod
    secrets: inherit
