name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      qa:
        type: boolean
        description: Redeploy QA
      production:
        type: boolean
        description: Redeploy Production
      production_canada:
        type: boolean
        description: Redeploy Production (Canada)
jobs:
  qa:
    name: QA
    if: inputs.qa
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA
      github_environment_url: https://qa-metabase.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: qa
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://metabase.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_canada:
    name: Production (Canada)
    if: inputs.production_canada
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Canada)
      github_environment_url: https://metabase.ca.hypothes.is/
      aws_region: ca-central-1
      elasticbeanstalk_application: metabase
      elasticbeanstalk_environment: prod
    secrets: inherit
